#!/bin/bash
# Source: http://askubuntu.com/a/450136

URGENT_VALUE=90

PREV_TOTAL=0
PREV_IDLE=0

cpuFile="/tmp/.cpu"

if [[ -f "${cpuFile}" ]]; then
  fileCont=$(cat "${cpuFile}")
  PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
  PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
fi

CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
unset CPU[0]                          # Discard the "cpu" prefix.
IDLE=${CPU[4]}                        # Get the idle CPU time.

# Calculate the total CPU time.
TOTAL=0

for VALUE in "${CPU[@]:0:4}"; do
  let "TOTAL=$TOTAL+$VALUE"
done
# Minhas alteracoes
BAR_1="▁"
BAR_2="▂"
BAR_3="▃"
BAR_4="▄"
BAR_5="▅"
BAR_6="▆"
BAR_7="▇"
QUA=14
if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
  if [[ $DIFF_USAGE -le $QUA ]]; then
	BAR=${BAR_1}
  elif [[ $DIFF_USAGE -le $((QUA*2)) ]]; then
	BAR=${BAR_2}
  elif [[ $DIFF_USAGE -le $((QUA*3)) ]]; then
	BAR=${BAR_3}
  elif [[ $DIFF_USAGE -le $((QUA*4)) ]]; then
	BAR=${BAR_4}
  elif [[ $DIFF_USAGE -le $((QUA*5)) ]]; then
	BAR=${BAR_5}
  elif [[ $DIFF_USAGE -le $((QUA*6)) ]]; then
	BAR=${BAR_6}
  else
	BAR=${BAR_7}
  fi	

  echo "${DIFF_USAGE}% ${BAR}"
  echo ""
else
  echo "?"
  echo "?"
  echo ""
fi

# Remember the total and idle CPU times for the next check.
echo "${TOTAL}" > "${cpuFile}"
echo "${IDLE}" >> "${cpuFile}"

if [[ "${DIFF_USAGE}" -gt 0 ]] && [[ "${DIFF_USAGE}" -gt "${URGENT_VALUE}" ]]; then
  exit 33
fi
